INFO 2024-12-08 14:15:21,646 autoreload Watching for file changes with StatReloader
INFO 2024-12-08 14:26:06,636 autoreload Watching for file changes with StatReloader
WARNING 2024-12-08 14:26:15,955 log Not Found: /
WARNING 2024-12-08 14:26:15,957 basehttp "GET / HTTP/1.1" 404 2450
WARNING 2024-12-08 14:26:16,243 log Not Found: /favicon.ico
WARNING 2024-12-08 14:26:16,244 basehttp "GET /favicon.ico HTTP/1.1" 404 2501
INFO 2024-12-08 14:26:40,297 basehttp "OPTIONS /common/login/ HTTP/1.1" 200 0
INFO 2024-12-08 14:26:40,789 basehttp "POST /common/login/ HTTP/1.1" 200 321
WARNING 2024-12-08 14:27:15,609 log Bad Request: /common/login/
WARNING 2024-12-08 14:27:15,611 basehttp "POST /common/login/ HTTP/1.1" 400 32
INFO 2024-12-08 14:28:05,063 basehttp "POST /common/login/ HTTP/1.1" 200 321
INFO 2024-12-08 14:28:14,091 backends Cookie Auth: User abinj2003@gmail.com (ID: 70e2dc2a-1a0f-41c7-a609-261a9b5b9778) authenticated successfully
ERROR 2024-12-08 14:28:14,171 log Internal Server Error: /common/currentuser/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: common_userprofile

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/common/views.py", line 89, in get
    userprofile = UserProfile.objects.get(user=user)
  File "/usr/local/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: common_userprofile
ERROR 2024-12-08 14:28:14,183 basehttp "GET /common/currentuser/ HTTP/1.1" 500 158902
INFO 2024-12-08 14:33:31,584 autoreload Watching for file changes with StatReloader
INFO 2024-12-08 14:36:31,671 backends Cookie Auth: User abinj2003@gmail.com (ID: 70e2dc2a-1a0f-41c7-a609-261a9b5b9778) authenticated successfully
ERROR 2024-12-08 14:36:31,726 log Internal Server Error: /common/currentuser/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: common_userprofile

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/common/views.py", line 89, in get
    userprofile = UserProfile.objects.get(user=user)
  File "/usr/local/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: common_userprofile
ERROR 2024-12-08 14:36:31,735 basehttp "GET /common/currentuser/ HTTP/1.1" 500 158902
INFO 2024-12-08 14:36:42,423 basehttp "POST /common/login/ HTTP/1.1" 200 321
INFO 2024-12-08 14:37:29,489 backends Cookie Auth: User abinj2003@gmail.com (ID: 70e2dc2a-1a0f-41c7-a609-261a9b5b9778) authenticated successfully
ERROR 2024-12-08 14:37:29,551 log Internal Server Error: /common/currentuser/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: common_userprofile

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/common/views.py", line 89, in get
    userprofile = UserProfile.objects.get(user=user)
  File "/usr/local/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: common_userprofile
ERROR 2024-12-08 14:37:29,561 basehttp "GET /common/currentuser/ HTTP/1.1" 500 158902
INFO 2024-12-08 14:40:54,770 basehttp "POST /common/signup/ HTTP/1.1" 201 88
INFO 2024-12-08 14:41:15,257 basehttp "POST /common/login/ HTTP/1.1" 200 321
INFO 2024-12-08 14:41:22,431 backends Cookie Auth: User maneeshmanu929@gmail.com (ID: f63bff92-e9b5-4051-a266-06929a164c53) authenticated successfully
ERROR 2024-12-08 14:41:22,512 log Internal Server Error: /common/currentuser/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/common/views.py", line 89, in get
    userprofile = UserProfile.objects.get(user=user)
  File "/usr/local/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
common.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
ERROR 2024-12-08 14:41:22,521 basehttp "GET /common/currentuser/ HTTP/1.1" 500 95061
WARNING 2024-12-08 14:44:52,851 log Bad Request: /common/signup/
WARNING 2024-12-08 14:44:52,855 basehttp "POST /common/signup/ HTTP/1.1" 400 57
INFO 2024-12-08 14:45:13,419 basehttp "POST /common/login/ HTTP/1.1" 200 321
INFO 2024-12-08 14:45:27,987 backends Cookie Auth: User maneeshmanu929@gmail.com (ID: f63bff92-e9b5-4051-a266-06929a164c53) authenticated successfully
ERROR 2024-12-08 14:45:28,111 log Internal Server Error: /common/currentuser/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/common/views.py", line 89, in get
    userprofile = UserProfile.objects.get(user=user)
  File "/usr/local/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
common.models.UserProfile.DoesNotExist: UserProfile matching query does not exist.
ERROR 2024-12-08 14:45:28,134 basehttp "GET /common/currentuser/ HTTP/1.1" 500 95061
INFO 2024-12-08 14:48:31,363 backends Cookie Auth: User maneeshmanu929@gmail.com (ID: f63bff92-e9b5-4051-a266-06929a164c53) authenticated successfully
INFO 2024-12-08 14:48:31,401 basehttp "POST /common/user-profile/ HTTP/1.1" 201 88
INFO 2024-12-08 14:48:48,970 backends Cookie Auth: User maneeshmanu929@gmail.com (ID: f63bff92-e9b5-4051-a266-06929a164c53) authenticated successfully
INFO 2024-12-08 14:48:48,972 basehttp "GET /common/currentuser/ HTTP/1.1" 200 176
INFO 2024-12-08 14:59:50,403 basehttp "OPTIONS /common/signup/ HTTP/1.1" 200 0
INFO 2024-12-08 14:59:51,066 basehttp "POST /common/signup/ HTTP/1.1" 201 88
INFO 2024-12-08 15:00:04,681 basehttp "OPTIONS /common/forgot-password/ HTTP/1.1" 200 0
INFO 2024-12-08 15:00:06,955 basehttp "POST /common/forgot-password/ HTTP/1.1" 200 44
INFO 2024-12-08 15:04:43,528 autoreload /app/root/settings.py changed, reloading.
INFO 2024-12-08 15:04:45,133 autoreload Watching for file changes with StatReloader
INFO 2024-12-08 15:06:58,024 autoreload Watching for file changes with StatReloader
INFO 2024-12-08 15:08:25,663 basehttp "POST /common/forgot-password/ HTTP/1.1" 200 44
INFO 2024-12-08 15:08:26,363 basehttp "POST /common/forgot-password/ HTTP/1.1" 200 44
INFO 2024-12-08 15:09:12,879 basehttp "OPTIONS /common/verify-otp/ HTTP/1.1" 200 0
WARNING 2024-12-08 15:09:12,883 log Bad Request: /common/verify-otp/
WARNING 2024-12-08 15:09:12,883 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
WARNING 2024-12-08 15:09:19,087 log Bad Request: /common/verify-otp/
WARNING 2024-12-08 15:09:19,087 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
WARNING 2024-12-08 15:09:20,317 log Bad Request: /common/verify-otp/
WARNING 2024-12-08 15:09:20,318 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
INFO 2024-12-09 03:37:59,718 autoreload Watching for file changes with StatReloader
INFO 2024-12-09 07:26:35,569 autoreload Watching for file changes with StatReloader
INFO 2024-12-09 07:29:23,097 autoreload Watching for file changes with StatReloader
INFO 2024-12-09 07:29:34,834 basehttp "OPTIONS /common/forgot-password/ HTTP/1.1" 200 0
INFO 2024-12-09 07:29:37,933 basehttp "POST /common/forgot-password/ HTTP/1.1" 200 44
INFO 2024-12-09 07:30:05,441 basehttp "OPTIONS /common/verify-otp/ HTTP/1.1" 200 0
WARNING 2024-12-09 07:30:05,442 log Bad Request: /common/verify-otp/
WARNING 2024-12-09 07:30:05,443 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
WARNING 2024-12-09 07:30:09,971 log Bad Request: /common/verify-otp/
WARNING 2024-12-09 07:30:09,972 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
WARNING 2024-12-09 07:30:10,120 log Bad Request: /common/verify-otp/
WARNING 2024-12-09 07:30:10,120 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
WARNING 2024-12-09 07:30:11,173 log Bad Request: /common/verify-otp/
WARNING 2024-12-09 07:30:11,173 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
WARNING 2024-12-09 07:30:11,359 log Bad Request: /common/verify-otp/
WARNING 2024-12-09 07:30:11,360 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
WARNING 2024-12-09 07:30:15,852 log Bad Request: /common/verify-otp/
WARNING 2024-12-09 07:30:15,853 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
WARNING 2024-12-09 07:30:16,541 log Bad Request: /common/verify-otp/
WARNING 2024-12-09 07:30:16,541 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
INFO 2024-12-09 07:47:21,292 basehttp "OPTIONS /common/forgot-password/ HTTP/1.1" 200 0
WARNING 2024-12-09 07:47:21,300 log Bad Request: /common/forgot-password/
WARNING 2024-12-09 07:47:21,300 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 70
INFO 2024-12-09 07:47:53,916 basehttp "POST /common/forgot-password/ HTTP/1.1" 200 44
INFO 2024-12-09 07:48:11,957 basehttp "POST /common/forgot-password/ HTTP/1.1" 200 44
WARNING 2024-12-09 07:48:14,940 log Bad Request: /common/forgot-password/
WARNING 2024-12-09 07:48:14,940 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 98
WARNING 2024-12-09 07:48:18,000 log Bad Request: /common/forgot-password/
WARNING 2024-12-09 07:48:18,000 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 98
INFO 2024-12-10 02:44:47,448 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 18:02:16,124 basehttp "OPTIONS /common/forgot-password/ HTTP/1.1" 200 0
WARNING 2024-12-10 18:02:16,225 log Bad Request: /common/forgot-password/
WARNING 2024-12-10 18:02:16,257 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 70
WARNING 2024-12-10 18:02:21,669 log Bad Request: /common/forgot-password/
WARNING 2024-12-10 18:02:21,670 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 88
INFO 2024-12-10 18:04:27,818 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 18:05:21,015 basehttp "OPTIONS /common/forgot-password/ HTTP/1.1" 200 0
INFO 2024-12-10 18:05:24,712 basehttp "POST /common/forgot-password/ HTTP/1.1" 200 44
INFO 2024-12-10 18:06:10,124 basehttp "OPTIONS /common/verify-otp/ HTTP/1.1" 200 0
WARNING 2024-12-10 18:06:10,139 log Bad Request: /common/verify-otp/
WARNING 2024-12-10 18:06:10,139 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
WARNING 2024-12-10 18:06:31,330 log Bad Request: /common/verify-otp/
WARNING 2024-12-10 18:06:31,333 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
WARNING 2024-12-10 18:06:42,728 log Bad Request: /common/verify-otp/
WARNING 2024-12-10 18:06:42,728 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
INFO 2024-12-10 18:08:49,775 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 18:09:32,082 basehttp "OPTIONS /common/forgot-password/ HTTP/1.1" 200 0
WARNING 2024-12-10 18:09:32,501 log Bad Request: /common/forgot-password/
WARNING 2024-12-10 18:09:32,501 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 98
INFO 2024-12-10 18:09:35,360 basehttp "POST /common/forgot-password/ HTTP/1.1" 200 44
INFO 2024-12-10 18:09:35,462 basehttp "POST /common/forgot-password/ HTTP/1.1" 200 44
INFO 2024-12-10 18:10:12,711 basehttp "OPTIONS /common/verify-otp/ HTTP/1.1" 200 0
WARNING 2024-12-10 18:10:12,714 log Bad Request: /common/verify-otp/
WARNING 2024-12-10 18:10:12,714 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
WARNING 2024-12-10 18:10:33,002 log Bad Request: /common/verify-otp/
WARNING 2024-12-10 18:10:33,004 basehttp "POST /common/verify-otp/ HTTP/1.1" 400 77
INFO 2024-12-10 18:14:22,015 autoreload Watching for file changes with StatReloader
WARNING 2024-12-10 18:20:30,576 log Bad Request: /common/forgot-password/
WARNING 2024-12-10 18:20:30,577 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 98
WARNING 2024-12-10 18:20:34,068 log Bad Request: /common/forgot-password/
WARNING 2024-12-10 18:20:34,069 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 98
WARNING 2024-12-10 18:20:42,203 log Bad Request: /common/forgot-password/
WARNING 2024-12-10 18:20:42,203 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 98
WARNING 2024-12-10 18:21:24,631 log Bad Request: /common/forgot-password/
WARNING 2024-12-10 18:21:24,635 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 98
WARNING 2024-12-10 18:22:00,796 log Bad Request: /common/forgot-password/
WARNING 2024-12-10 18:22:00,798 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 98
WARNING 2024-12-10 18:22:05,591 log Bad Request: /common/forgot-password/
WARNING 2024-12-10 18:22:05,592 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 98
WARNING 2024-12-10 18:22:36,758 log Bad Request: /common/forgot-password/
WARNING 2024-12-10 18:22:36,758 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 88
WARNING 2024-12-10 18:23:10,468 log Bad Request: /common/forgot-password/
WARNING 2024-12-10 18:23:10,469 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 98
WARNING 2024-12-10 18:23:56,325 log Bad Request: /common/forgot-password/
WARNING 2024-12-10 18:23:56,326 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 98
INFO 2024-12-10 18:26:47,570 autoreload Watching for file changes with StatReloader
WARNING 2024-12-10 18:27:52,383 log Bad Request: /common/forgot-password/
WARNING 2024-12-10 18:27:52,383 basehttp "POST /common/forgot-password/ HTTP/1.1" 400 98
INFO 2024-12-11 02:50:23,414 autoreload Watching for file changes with StatReloader
INFO 2024-12-11 08:09:48,884 autoreload Watching for file changes with StatReloader
INFO 2024-12-12 17:13:16,544 autoreload Watching for file changes with StatReloader
INFO 2024-12-13 03:43:24,291 autoreload Watching for file changes with StatReloader
INFO 2024-12-13 08:00:49,879 autoreload Watching for file changes with StatReloader
INFO 2024-12-14 02:50:40,809 autoreload Watching for file changes with StatReloader
INFO 2024-12-14 05:07:57,953 autoreload /app/common/handlers.py changed, reloading.
INFO 2024-12-14 05:07:59,637 autoreload Watching for file changes with StatReloader
INFO 2024-12-14 05:09:57,943 autoreload Watching for file changes with StatReloader
INFO 2024-12-14 05:11:15,433 autoreload Watching for file changes with StatReloader
WARNING 2024-12-14 05:12:19,153 backends No token found in cookies for authentication.
WARNING 2024-12-14 05:12:19,182 log Forbidden: /common/logout/
WARNING 2024-12-14 05:12:19,189 basehttp "POST /common/logout/ HTTP/1.1" 403 58
INFO 2024-12-14 05:12:46,510 basehttp "OPTIONS /common/forgot-password/ HTTP/1.1" 200 0
INFO 2024-12-14 05:12:50,771 basehttp "POST /common/forgot-password/ HTTP/1.1" 200 44
INFO 2024-12-14 05:13:38,752 basehttp "OPTIONS /common/verify-otp/ HTTP/1.1" 200 0
INFO 2024-12-14 05:13:39,466 basehttp "POST /common/verify-otp/ HTTP/1.1" 200 42
INFO 2024-12-14 05:13:52,457 basehttp "OPTIONS /common/login/ HTTP/1.1" 200 0
INFO 2024-12-14 05:13:53,161 basehttp "POST /common/login/ HTTP/1.1" 200 321
INFO 2024-12-14 05:14:08,768 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 05:14:08,769 basehttp "POST /common/logout/ HTTP/1.1" 200 36
WARNING 2024-12-14 05:58:55,380 backends No token found in cookies for authentication.
WARNING 2024-12-14 05:58:55,384 log Forbidden: /common/logout/
WARNING 2024-12-14 05:58:55,384 basehttp "POST /common/logout/ HTTP/1.1" 403 58
ERROR 2024-12-14 05:59:55,799 log Internal Server Error: /api/products/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: products_product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/products/views.py", line 49, in get
    if not products.exists():
           ~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/query.py", line 660, in has_results
    return compiler.has_results()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: products_product
ERROR 2024-12-14 05:59:55,809 basehttp "GET /api/products/ HTTP/1.1" 500 146281
WARNING 2024-12-14 06:01:06,830 backends No token found in cookies for authentication.
WARNING 2024-12-14 06:01:06,832 log Forbidden: /api/products/
WARNING 2024-12-14 06:01:06,833 basehttp "POST /api/products/ HTTP/1.1" 403 58
INFO 2024-12-14 06:02:17,488 basehttp "POST /common/login/ HTTP/1.1" 200 321
WARNING 2024-12-14 06:02:35,993 backends No token found in cookies for authentication.
WARNING 2024-12-14 06:02:35,994 log Forbidden: /api/products/
WARNING 2024-12-14 06:02:35,994 basehttp "POST /api/products/ HTTP/1.1" 403 58
WARNING 2024-12-14 06:02:49,386 backends No token found in cookies for authentication.
WARNING 2024-12-14 06:02:49,387 log Forbidden: /common/currentuser/
WARNING 2024-12-14 06:02:49,387 basehttp "GET /common/currentuser/ HTTP/1.1" 403 58
WARNING 2024-12-14 06:03:05,074 log Bad Request: /common/login/
WARNING 2024-12-14 06:03:05,074 basehttp "POST /common/login/ HTTP/1.1" 400 32
INFO 2024-12-14 06:03:49,308 basehttp "POST /common/login/ HTTP/1.1" 200 321
INFO 2024-12-14 06:03:53,732 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:03:53,736 basehttp "GET /common/currentuser/ HTTP/1.1" 200 144
INFO 2024-12-14 06:03:54,905 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:03:54,905 basehttp "GET /common/currentuser/ HTTP/1.1" 200 144
INFO 2024-12-14 06:03:55,654 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:03:55,655 basehttp "GET /common/currentuser/ HTTP/1.1" 200 144
INFO 2024-12-14 06:03:56,510 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:03:56,511 basehttp "GET /common/currentuser/ HTTP/1.1" 200 144
INFO 2024-12-14 06:04:17,243 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:04:17,244 basehttp "GET /common/currentuser/ HTTP/1.1" 200 144
INFO 2024-12-14 06:04:18,215 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:04:18,215 basehttp "GET /common/currentuser/ HTTP/1.1" 200 144
INFO 2024-12-14 06:04:18,826 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:04:18,827 basehttp "GET /common/currentuser/ HTTP/1.1" 200 144
INFO 2024-12-14 06:04:36,717 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:04:36,717 views Authenticated user from view productss: abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e)
ERROR 2024-12-14 06:04:36,784 log Internal Server Error: /api/products/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: products_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/products/views.py", line 61, in post
    if serializer.is_valid():
       ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/serializers.py", line 499, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/relations.py", line 155, in run_validation
    return super().run_validation(data)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/fields.py", line 538, in run_validation
    value = self.to_internal_value(data)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/relations.py", line 259, in to_internal_value
    return queryset.get(pk=data)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: products_category
ERROR 2024-12-14 06:04:36,789 basehttp "POST /api/products/ HTTP/1.1" 500 180842
INFO 2024-12-14 06:06:41,372 autoreload Watching for file changes with StatReloader
WARNING 2024-12-14 06:30:49,669 log Not Found: /
WARNING 2024-12-14 06:30:49,673 basehttp "GET / HTTP/1.1" 404 2450
WARNING 2024-12-14 06:30:49,880 log Not Found: /favicon.ico
WARNING 2024-12-14 06:30:49,881 basehttp "GET /favicon.ico HTTP/1.1" 404 2501
INFO 2024-12-14 06:30:55,483 basehttp "GET /admin/ HTTP/1.1" 302 0
INFO 2024-12-14 06:30:55,577 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4157
INFO 2024-12-14 06:30:55,683 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2024-12-14 06:30:55,684 basehttp "GET /static/admin/css/login.css HTTP/1.1" 200 951
INFO 2024-12-14 06:30:55,684 basehttp "GET /static/admin/css/base.css HTTP/1.1" 200 22092
INFO 2024-12-14 06:30:55,685 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2024-12-14 06:30:55,685 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
INFO 2024-12-14 06:30:55,686 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2024-12-14 06:30:55,687 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
INFO 2024-12-14 06:31:14,631 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4329
INFO 2024-12-14 06:31:21,621 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4329
INFO 2024-12-14 06:36:56,497 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4157
ERROR 2024-12-14 06:37:08,168 log Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 444, in login
    return LoginView.as_view(**defaults)(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/auth/views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/auth/views.py", line 108, in form_valid
    auth_login(self.request, form.get_user())
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/auth/__init__.py", line 126, in login
    request.session.cycle_key()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/base.py", line 432, in cycle_key
    self.create()
    ~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/db.py", line 70, in create
    self._session_key = self._get_new_session_key()
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/base.py", line 196, in _get_new_session_key
    if not self.exists(session_key):
           ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/db.py", line 63, in exists
    return self.model.objects.filter(session_key=session_key).exists()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/query.py", line 660, in has_results
    return compiler.has_results()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
ERROR 2024-12-14 06:37:08,185 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 500 215846
WARNING 2024-12-14 06:37:08,289 log Not Found: /favicon.ico
WARNING 2024-12-14 06:37:08,290 basehttp "GET /favicon.ico HTTP/1.1" 404 2501
INFO 2024-12-14 06:37:17,446 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4157
ERROR 2024-12-14 06:45:04,922 log Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 444, in login
    return LoginView.as_view(**defaults)(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/auth/views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/auth/views.py", line 108, in form_valid
    auth_login(self.request, form.get_user())
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/auth/__init__.py", line 126, in login
    request.session.cycle_key()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/base.py", line 432, in cycle_key
    self.create()
    ~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/db.py", line 70, in create
    self._session_key = self._get_new_session_key()
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/base.py", line 196, in _get_new_session_key
    if not self.exists(session_key):
           ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/db.py", line 63, in exists
    return self.model.objects.filter(session_key=session_key).exists()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/query.py", line 660, in has_results
    return compiler.has_results()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
ERROR 2024-12-14 06:45:04,934 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 500 215846
WARNING 2024-12-14 06:45:23,304 log Not Found: /
WARNING 2024-12-14 06:45:23,305 basehttp "GET / HTTP/1.1" 404 2450
INFO 2024-12-14 06:45:29,241 basehttp "GET /admin/ HTTP/1.1" 302 0
INFO 2024-12-14 06:45:29,274 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4157
INFO 2024-12-14 06:45:29,351 basehttp "GET /static/admin/css/base.css HTTP/1.1" 200 22092
INFO 2024-12-14 06:45:29,355 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
INFO 2024-12-14 06:45:29,361 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2024-12-14 06:45:29,363 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2024-12-14 06:45:29,363 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2024-12-14 06:45:29,363 basehttp "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2024-12-14 06:45:29,364 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
ERROR 2024-12-14 06:45:32,029 log Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 444, in login
    return LoginView.as_view(**defaults)(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/auth/views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/auth/views.py", line 108, in form_valid
    auth_login(self.request, form.get_user())
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/auth/__init__.py", line 126, in login
    request.session.cycle_key()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/base.py", line 432, in cycle_key
    self.create()
    ~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/db.py", line 70, in create
    self._session_key = self._get_new_session_key()
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/base.py", line 196, in _get_new_session_key
    if not self.exists(session_key):
           ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/db.py", line 63, in exists
    return self.model.objects.filter(session_key=session_key).exists()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/query.py", line 660, in has_results
    return compiler.has_results()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
ERROR 2024-12-14 06:45:32,036 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 500 215846
INFO 2024-12-14 06:48:28,008 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4157
INFO 2024-12-14 06:48:28,113 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
ERROR 2024-12-14 06:49:31,835 log Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 444, in login
    return LoginView.as_view(**defaults)(request)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/auth/views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/auth/views.py", line 108, in form_valid
    auth_login(self.request, form.get_user())
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/auth/__init__.py", line 126, in login
    request.session.cycle_key()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/base.py", line 432, in cycle_key
    self.create()
    ~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/db.py", line 70, in create
    self._session_key = self._get_new_session_key()
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/base.py", line 196, in _get_new_session_key
    if not self.exists(session_key):
           ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/sessions/backends/db.py", line 63, in exists
    return self.model.objects.filter(session_key=session_key).exists()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/query.py", line 660, in has_results
    return compiler.has_results()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
ERROR 2024-12-14 06:49:31,846 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 500 215846
INFO 2024-12-14 06:50:37,982 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4157
INFO 2024-12-14 06:50:40,183 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2024-12-14 06:50:40,227 basehttp "GET /admin/ HTTP/1.1" 200 12521
INFO 2024-12-14 06:50:40,275 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2024-12-14 06:50:40,287 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2024-12-14 06:50:40,289 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2024-12-14 06:50:53,083 basehttp "GET /admin/products/category/add/ HTTP/1.1" 200 12816
INFO 2024-12-14 06:50:53,156 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 200 8794
INFO 2024-12-14 06:50:53,167 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2024-12-14 06:50:53,167 basehttp "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2024-12-14 06:50:53,170 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
INFO 2024-12-14 06:50:53,173 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2024-12-14 06:50:53,175 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2024-12-14 06:50:53,175 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2024-12-14 06:50:53,176 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2024-12-14 06:50:53,178 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2024-12-14 06:50:53,179 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2024-12-14 06:50:53,183 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2024-12-14 06:50:53,186 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2024-12-14 06:50:53,199 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 200 11564
ERROR 2024-12-14 06:50:59,306 log Internal Server Error: /admin/products/category/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: products_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1961, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1820, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1871, in _changeform_view
    self.save_model(request, new_object, form, not add)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1294, in save_model
    obj.save()
    ~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 1160, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "/usr/local/lib/python3.13/site-packages/django/db/models/base.py", line 1201, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: products_category
ERROR 2024-12-14 06:50:59,317 basehttp "POST /admin/products/category/add/ HTTP/1.1" 500 197368
INFO 2024-12-14 06:51:05,860 basehttp "GET /admin/products/category/add/ HTTP/1.1" 200 12816
INFO 2024-12-14 06:52:48,646 basehttp "POST /admin/products/category/add/ HTTP/1.1" 302 0
INFO 2024-12-14 06:52:48,669 basehttp "GET /admin/products/category/add/ HTTP/1.1" 200 13055
INFO 2024-12-14 06:52:48,744 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2024-12-14 06:52:48,799 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2024-12-14 06:54:30,217 basehttp "GET /admin/products/category/ HTTP/1.1" 200 13326
INFO 2024-12-14 06:54:30,270 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2024-12-14 06:54:30,282 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2024-12-14 06:54:30,295 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2024-12-14 06:54:30,343 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2024-12-14 06:54:50,800 basehttp "POST /common/login/ HTTP/1.1" 200 321
INFO 2024-12-14 06:54:57,350 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:54:57,350 views Authenticated user from view productss: abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e)
WARNING 2024-12-14 06:54:57,382 log Bad Request: /api/products/
WARNING 2024-12-14 06:54:57,383 basehttp "POST /api/products/ HTTP/1.1" 400 137
WARNING 2024-12-14 06:55:32,227 log Bad Request: /common/signup/
WARNING 2024-12-14 06:55:32,228 basehttp "POST /common/signup/ HTTP/1.1" 400 57
INFO 2024-12-14 06:55:44,493 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:55:44,505 basehttp "GET /common/currentuser/ HTTP/1.1" 200 144
INFO 2024-12-14 06:56:09,511 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:56:09,511 views Authenticated user from view productss: abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e)
INFO 2024-12-14 06:56:09,540 basehttp "POST /api/products/ HTTP/1.1" 201 344
INFO 2024-12-14 06:56:28,479 basehttp "POST /common/login/ HTTP/1.1" 200 321
INFO 2024-12-14 06:56:37,163 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:56:37,165 basehttp "GET /common/currentuser/ HTTP/1.1" 200 144
INFO 2024-12-14 06:57:07,010 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:57:07,010 views Authenticated user from view productss: abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e)
INFO 2024-12-14 06:57:07,028 basehttp "POST /api/products/ HTTP/1.1" 201 344
INFO 2024-12-14 06:57:26,345 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
INFO 2024-12-14 06:57:26,346 views Authenticated user from view productss: abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e)
INFO 2024-12-14 06:57:26,362 basehttp "POST /api/products/ HTTP/1.1" 201 344
INFO 2024-12-14 06:58:00,243 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 07:07:13,633 backends Cookie Auth: User abinj2003@gmail.com (ID: cd0f8166-51fd-42e4-9b3b-3ab21b8c870e) authenticated successfully
ERROR 2024-12-14 07:07:13,736 log Internal Server Error: /api/products/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: ProductAPIView.delete() missing 1 required positional argument: 'product_id'
ERROR 2024-12-14 07:07:13,741 basehttp "DELETE /api/products/ HTTP/1.1" 500 82306
INFO 2024-12-14 07:33:47,460 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2024-12-14 07:33:47,503 basehttp "GET /admin/ HTTP/1.1" 200 12903
INFO 2024-12-14 07:33:47,643 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2024-12-14 07:33:47,643 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2024-12-14 07:57:48,574 autoreload Watching for file changes with StatReloader
INFO 2024-12-14 11:59:21,755 autoreload Watching for file changes with StatReloader
INFO 2024-12-14 13:06:06,879 autoreload Watching for file changes with StatReloader
INFO 2024-12-14 13:09:25,676 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:25,678 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:25,678 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:25,678 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:25,679 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:25,679 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:25,685 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:25,686 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:40,281 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:40,282 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:40,283 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:40,293 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:40,305 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:40,305 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:40,306 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:40,306 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:51,465 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:51,466 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:51,469 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:51,472 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:51,472 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:51,475 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:51,477 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:09:51,478 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:04,382 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:04,382 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:04,392 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:04,395 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:04,398 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:04,400 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:04,401 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:04,408 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:10,064 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:10,065 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:10,066 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:10,067 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:10,076 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:10,080 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:10,080 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:10:10,081 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:33:42,319 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:33:42,319 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:33:58,765 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:33:58,767 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:34:48,493 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:38:06,064 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:38:06,064 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:38:41,232 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:38:41,241 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:38:48,829 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:38:48,829 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:39:30,577 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:39:30,577 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:41:02,317 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:41:02,317 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:41:19,016 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:41:19,016 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:46:06,618 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:46:06,660 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:46:40,479 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:46:40,555 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:49:47,680 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 13:49:55,400 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:26:11,556 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:26:11,557 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:26:11,582 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:26:11,670 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:31:26,897 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:31:26,897 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:32:42,572 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:32:49,633 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:32:49,639 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:39:49,895 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:51:48,545 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:51:48,547 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:52:30,832 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 14:52:43,221 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:37:48,108 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:37:48,114 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:37:48,115 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:37:48,115 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:38:06,761 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:38:32,722 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:38:36,267 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:38:36,276 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:38:36,277 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:38:36,277 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:38:56,032 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:39:18,386 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:39:21,195 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:39:21,197 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:39:21,199 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:39:21,202 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:39:50,308 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:49:44,128 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:49:44,144 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:49:44,145 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:49:44,146 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:49:44,150 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:49:44,153 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:16,968 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:19,318 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:19,326 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:19,333 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:19,341 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:19,341 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:19,342 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:29,216 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:29,221 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:29,228 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:29,228 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:29,265 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:29,271 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:50,150 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:50,205 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:50,220 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:50,225 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:50,238 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:50:50,243 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:01,039 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:01,041 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:01,046 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:01,051 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:01,054 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:01,054 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:22,316 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:45,651 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:45,665 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:45,676 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:45,676 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:45,676 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:45,810 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:51:58,041 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:15,760 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:15,761 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:15,765 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:15,766 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:15,830 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:15,830 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:20,992 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:21,003 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:21,008 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:21,035 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:21,071 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:21,075 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:23,797 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:23,799 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:23,800 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:23,806 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:23,812 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:23,812 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:25,772 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:25,780 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:25,780 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:25,783 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:25,789 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-14 16:55:25,790 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2024-12-15 10:02:33,247 autoreload Watching for file changes with StatReloader
INFO 2024-12-15 16:41:50,380 autoreload Watching for file changes with StatReloader
INFO 2024-12-15 19:17:50,331 autoreload Watching for file changes with StatReloader
INFO 2024-12-16 08:33:10,279 autoreload Watching for file changes with StatReloader
INFO 2024-12-16 15:01:41,683 autoreload Watching for file changes with StatReloader
INFO 2024-12-16 15:21:39,469 autoreload Watching for file changes with StatReloader
INFO 2024-12-16 15:25:35,941 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 04:35:13,998 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 11:42:56,618 autoreload Watching for file changes with StatReloader
INFO 2024-12-19 07:51:24,132 autoreload Watching for file changes with StatReloader
INFO 2024-12-20 14:18:02,038 autoreload Watching for file changes with StatReloader
INFO 2024-12-22 09:55:22,691 autoreload Watching for file changes with StatReloader
INFO 2024-12-22 11:58:09,114 autoreload Watching for file changes with StatReloader
INFO 2024-12-23 08:53:52,079 autoreload Watching for file changes with StatReloader
INFO 2024-12-24 04:27:47,590 autoreload Watching for file changes with StatReloader
INFO 2024-12-24 08:23:53,721 autoreload Watching for file changes with StatReloader
INFO 2024-12-26 12:36:48,585 autoreload Watching for file changes with StatReloader
INFO 2024-12-26 13:04:39,712 autoreload Watching for file changes with StatReloader
INFO 2024-12-29 06:23:12,298 autoreload Watching for file changes with StatReloader
INFO 2024-12-30 03:46:35,027 autoreload Watching for file changes with StatReloader
INFO 2024-12-30 11:08:21,137 autoreload Watching for file changes with StatReloader
INFO 2025-01-01 16:22:23,138 autoreload Watching for file changes with StatReloader
INFO 2025-01-03 04:14:03,640 autoreload Watching for file changes with StatReloader
INFO 2025-01-03 16:34:11,649 autoreload Watching for file changes with StatReloader
INFO 2025-01-04 04:04:19,570 autoreload Watching for file changes with StatReloader
INFO 2025-01-05 02:55:40,732 autoreload Watching for file changes with StatReloader
INFO 2025-01-06 09:44:28,491 autoreload Watching for file changes with StatReloader
INFO 2025-01-06 13:48:49,559 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 04:16:17,235 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 08:46:55,811 autoreload Watching for file changes with StatReloader
INFO 2025-01-09 08:21:00,443 autoreload Watching for file changes with StatReloader
INFO 2025-01-09 12:03:22,519 autoreload Watching for file changes with StatReloader
INFO 2025-01-09 17:37:58,057 autoreload Watching for file changes with StatReloader
INFO 2025-01-10 05:08:36,887 autoreload Watching for file changes with StatReloader
INFO 2025-01-10 05:18:52,486 autoreload Watching for file changes with StatReloader
INFO 2025-01-11 06:06:01,187 autoreload Watching for file changes with StatReloader
INFO 2025-01-12 06:21:39,206 autoreload Watching for file changes with StatReloader
INFO 2025-01-12 15:45:31,034 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2025-01-12 15:45:31,031 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2025-01-12 15:45:31,038 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2025-01-12 15:45:31,038 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2025-01-12 15:45:31,038 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2025-01-12 15:45:31,038 basehttp "GET /api/products/ HTTP/1.1" 200 1012
INFO 2025-01-13 11:59:23,796 autoreload Watching for file changes with StatReloader
INFO 2025-01-13 12:34:15,923 autoreload Watching for file changes with StatReloader
INFO 2025-01-13 16:57:58,442 autoreload Watching for file changes with StatReloader
INFO 2025-01-14 03:44:42,389 autoreload Watching for file changes with StatReloader
INFO 2025-01-14 08:57:46,180 autoreload Watching for file changes with StatReloader
INFO 2025-01-14 13:48:45,679 autoreload Watching for file changes with StatReloader
INFO 2025-01-14 17:36:56,225 autoreload Watching for file changes with StatReloader
INFO 2025-01-14 17:47:20,585 autoreload Watching for file changes with StatReloader
INFO 2025-01-15 02:11:39,002 autoreload Watching for file changes with StatReloader
INFO 2025-01-15 07:34:36,444 autoreload Watching for file changes with StatReloader
WARNING 2025-01-15 09:15:18,947 log Not Found: /blog/
WARNING 2025-01-15 09:15:18,961 basehttp "GET /blog/ HTTP/1.1" 404 2485
WARNING 2025-01-15 09:15:19,018 log Not Found: /favicon.ico
WARNING 2025-01-15 09:15:19,018 basehttp "GET /favicon.ico HTTP/1.1" 404 2503
INFO 2025-01-15 12:09:09,630 autoreload Watching for file changes with StatReloader
INFO 2025-01-15 14:06:52,288 autoreload Watching for file changes with StatReloader
INFO 2025-01-16 08:25:33,829 autoreload Watching for file changes with StatReloader
INFO 2025-01-16 19:56:06,530 autoreload Watching for file changes with StatReloader
INFO 2025-01-17 07:38:13,352 autoreload Watching for file changes with StatReloader
INFO 2025-01-17 08:56:16,987 autoreload Watching for file changes with StatReloader
INFO 2025-01-17 13:36:33,141 autoreload Watching for file changes with StatReloader
INFO 2025-01-17 19:55:34,718 autoreload Watching for file changes with StatReloader
INFO 2025-01-17 20:40:32,447 autoreload Watching for file changes with StatReloader
INFO 2025-01-20 02:33:29,713 autoreload Watching for file changes with StatReloader
INFO 2025-01-20 13:03:14,467 autoreload Watching for file changes with StatReloader
INFO 2025-01-20 15:46:59,651 autoreload Watching for file changes with StatReloader
INFO 2025-01-21 03:55:56,956 autoreload Watching for file changes with StatReloader
INFO 2025-01-21 07:12:32,765 autoreload Watching for file changes with StatReloader
INFO 2025-01-21 09:13:01,654 autoreload Watching for file changes with StatReloader
INFO 2025-01-21 15:39:32,087 autoreload Watching for file changes with StatReloader
INFO 2025-01-22 06:04:52,891 autoreload Watching for file changes with StatReloader
INFO 2025-01-22 10:20:29,795 autoreload Watching for file changes with StatReloader
INFO 2025-01-22 15:23:08,197 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 03:55:52,148 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 04:16:46,549 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 14:10:53,037 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 14:58:31,970 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 04:01:10,492 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 07:16:45,391 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 08:00:21,180 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 09:43:03,915 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 10:20:26,020 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 15:07:31,566 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 15:09:18,624 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 16:25:11,844 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 17:38:18,932 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 23:07:00,364 autoreload Watching for file changes with StatReloader
INFO 2025-01-25 00:13:37,899 autoreload Watching for file changes with StatReloader
INFO 2025-01-25 02:26:50,125 autoreload Watching for file changes with StatReloader
INFO 2025-01-25 07:10:59,522 autoreload Watching for file changes with StatReloader
INFO 2025-01-25 07:45:44,628 autoreload Watching for file changes with StatReloader
INFO 2025-01-25 08:26:09,843 autoreload Watching for file changes with StatReloader
INFO 2025-01-25 09:01:44,650 autoreload Watching for file changes with StatReloader
INFO 2025-01-25 09:58:43,037 autoreload Watching for file changes with StatReloader
WARNING 2025-01-25 09:59:26,069 backends No token found in cookies for authentication.
WARNING 2025-01-25 09:59:26,071 log Forbidden: /common/logout/
WARNING 2025-01-25 09:59:26,072 basehttp "POST /common/logout/ HTTP/1.1" 403 58
INFO 2025-01-25 15:42:29,805 autoreload Watching for file changes with StatReloader
INFO 2025-01-25 17:52:41,299 autoreload Watching for file changes with StatReloader
